# Generated by Django 6.1 on 2026-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='tracking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
