# Generated by Django 6.1 on 2026-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
