# Generated by Django 6.1 on 2026-09-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.order'),
        ),
    ]
